name: Prettier
  
on:
  workflow_call:

  workflow_dispatch:
    inputs:
      do_formatting:
        description: "Run prettier inplace formatting and commit the result"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.do_formatting != 'true' }}
        with:
          dry: True
          prettier_options: --check resources/Structs.json resources/EntitySubclasses.json resources/RoomCodes.json

      - uses: creyD/prettier_action@v4.3
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.do_formatting == 'true' }}
        with:
          prettier_options: --write resources/Structs.json resources/EntitySubclasses.json resources/RoomCodes.json
          commit_message: "Automated prettier changes"

      - uses: actions/upload-artifact@v4
        if: ${{ success() && (github.event_name != 'workflow_dispatch' || github.event.inputs.do_formatting == 'true') }}
        with:
          name: json
          path: |
              resources/Structs.json
              resources/EntitySubclasses.json
              resources/RoomCodes.json
          retention-days: 1
